# Generated by Django 6.1.1 on 2026-10-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_DB',
            fields=[
                ('Vehicle_No', models.CharField(primary_key=True, serialize=False)),
                ('Owner', models.CharField(max_length=10)),
                ('Vehicle_Model', models.CharField()),
                ('Vehicle_Color', models.CharField()),
                ('Lisence', models.CharField()),
                ('Insurance', models.CharField()),
                ('Mobile_No', models.IntegerField()),
                ('Address', models.TextField()),
            ],
        ),
    ]
